CREATE DATABASE IMDb
USE IMDb

CREATE TABLE Directors(
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(100),
	Surname NVARCHAR(120)
	
	)

CREATE TABLE Movies(
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(100),
	Duration INT,
	DirectorId INT CONSTRAINT FK_DirectorsId FOREIGN KEY REFERENCES Directors(Id)
)

CREATE TABLE Actors(
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(100),
	Surname NVARCHAR(120)
)


CREATE TABLE MovieActors(
	Id INT PRIMARY KEY IDENTITY,
	MovieId INT CONSTRAINT FK_MovieId FOREIGN KEY REFERENCES Movies(Id),
	ActorId INT CONSTRAINT FK_ActorId FOREIGN KEY REFERENCES Actors(Id)
)

CREATE TABLE Genres(
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(100)
)

CREATE TABLE MovieGenres(
	Id INT PRIMARY KEY IDENTITY,
	MovieId INT CONSTRAINT FK_MovieGenresId FOREIGN KEY REFERENCES Movies(Id),
	GenreId INT CONSTRAINT FK_GenreId FOREIGN KEY REFERENCES Genres(Id)
)







	



